### ISSUE TITLE
Type instantiation is excessively deep

### ISSUE THREAD

**Issue by swarnakumar** [ctrlplusb/easy-peasy#227]
I just upgraded from 2.5.0 to 2.6.5.

Typescript is not compiling. 

My Code:
```const logged_in = useStoreState(store => store.auth.get_login_status());```

The message is 
```Type instantiation is excessively deep and possibly infinite```

This was working fine earlier.

**Comment by ctrlplusb** [comment]
Hi @swarnakumar 

What version of TS are u using?

**Comment by swarnakumar** [comment]
3.5.1

**Comment by swarnakumar** [comment]
There was an unused import of select in my ducks file where I was declaring the model.

The error vanished when I removed the import.

Closing the issue.

**Comment by swarnakumar** [comment]
I am seeing this issue still. And its intermittent.

The fix on my previous comment, ensured compilation happens. My project was bootstrapped using CRA.

 But VS Code screams quite a bit about this.

I am unable to figure out what's happening.

**Comment by strobox** [comment]
Strange error. Also disappeared after some manipulations (i.e. typescript upgrade)

**Comment by danielmahon** [comment]
Had this issue too, removing `node_modules` `yarn.lock` and reinstalling fixed it for now... using typescript@3.5.2 and easy-peasy@2.6.5

**Comment by danielmahon** [comment]
Downgrading didn't help, not sure why all of a sudden TS is throwing this error. Seems to go away if I get stricter with the types(which I suppose is what it wants).
```ts
import { Action, action } from 'easy-peasy';

export interface DataModel {
  screens: any[]; // changed from "any"
  files: any[]; // changed from "any"
  set: Action<DataModel, Partial<DataModel>>;
}

const data: DataModel = {
  screens: [],
  files: [],
  set: action((state, payload) => {
    return { ...state, ...payload };
  }),
};

export { data };
```

**Comment by ctrlplusb** [comment]
Ah, interesting. I don't test for the any case. Also, are any of you using generic interfaces or types in your models?

**Comment by ctrlplusb** [comment]
I am gonna do some more testing and work on the definitions 👍

**Comment by danielmahon** [comment]
Popped up again in VSCode, though TS seems to be compiling fine (create-react-app project). Maybe there's some discrepancy in VSCode?

**Comment by swarnakumar** [comment]
This got even weirder for me

Error pops up when:
```
const state = useStoreState(state => state.auth.something);
const action = useStoreActions(actions => state.auth.someAction);
```

Very weirdly, error stops when I reverse the two statements:
```
const action = useStoreActions(actions => state.auth.someAction);
const state = useStoreState(state => state.auth.something);
```

Again, the code's compiling fine (CRA project).

**Comment by ctrlplusb** [comment]
Hi all;

I have reworked the definitions quite a bit in V3, introducing a depth limit to the State/Actions types. This may help prevent some cases of the "excessively deep" errors.

Also, in regards to the excessively deep issue, I [read](https://github.com/pirix-gh/ts-toolbelt/issues/13#issuecomment-507292269) that you should try delete your node_modules dir as TS stores a cache in there.

I have done this updates on the v3 branch.

One area where the type definitions aren't working is for generic model interfaces though. This needs more investigation.

I have publish v3 as an alpha and would appreciate if any of you could update to this version and let me know if the problems persist.

```
npm install easy-peasy@3.0.0-alpha.0
```

FYI, v3 requires Typescript >= 3.5.1

**Comment by ctrlplusb** [comment]
Ok, I got a really complex case of a generic interface model working now too. Types are waaaay cleaner than before. 👍

```
npm install easy-peasy@3.0.0-alpha.1
```

**Comment by ctrlplusb** [comment]
@danielmahon @swarnakumar @strobox 

Quite keen to hear your guys experience on the alpha. 👍

**Comment by ctrlplusb** [comment]
@danielmahon - I added a test case for using `any` in a store too. 👍

**Comment by danielmahon** [comment]
@ctrlplusb Currently "keyboard catting" my way through July 4th deadlines, then I will definitely check out the alpha, thanks for looking into it so quickly! In the meantime...

![200w](https://user-images.githubusercontent.com/1088089/60626288-49d8d080-9db8-11e9-80cc-baa0e1b9db16.gif)

**Comment by ctrlplusb** [comment]
@pb03 you may be interested

**Comment by swarnakumar** [comment]
I just installed the new alpha. The errors have vanished.

**Comment by ctrlplusb** [comment]
Yeah apologies @swarnakumar - you will need to migrate to using `listenTo` configured actions/thunks to replace the listen API.

The [2.4.0 Release Notes](https://github.com/ctrlplusb/easy-peasy/releases/tag/v2.4.0) show you how to do the migration. 👍

Doing this deprecation, and using the new API opened up a lot of benefits that made me decide it was the right move. I am sorry about the API churn over 2.x, but with 3.x I plan to keep things _very_ stable.

**Comment by swarnakumar** [comment]
No, there's notice, so that's okay. Let me finish the migration, so I can see what else pops up.

A couple other things I discovered when I am using the alpha:

1. I have a model which has actions called ```push``` and ```pop```. They don't work anymore. The other actions work. I had to rename these two actions, and then errors vanish.

2. I have a thunk defined as follows:
```
fetch_listing: Thunk<StateInterface, number | undefined | null, Injections>;
```

And I was calling it ```fetch_listing(null)```. This doesn't work anymore. 

The TS definitions now expect a ```number & null``` instead of ```number | null```

A related question: what should the typing be if I have an optional payload to a thunk? In the above example, I want to support both ```fetch_listing()``` and ```fetch_listing(10)```.

**Comment by ctrlplusb** [comment]
@swarnakumar - awesome! thanks for this super valuable feedback.

> I have a model which has actions called push and pop. They don't work anymore. The other actions work. I had to rename these two actions, and then errors vanish.

Wow! Interesting case. I filter out Array\<any\> via my Actions type. I have a feeling duck typing is being used, so because you added a push and pop it got picked up as an Array. I will look into this further.

> However, this particular listener was listening to an action on the same model. And when I try to set a listenTo, model isn't yet defined. Gets a bit circular.

I plan on improving this API, allowing you to define an action that will receive actions instead.

```javascript
onTodoAdded: action(
  () => ...,
  {
    listenTo: (actions, storeActions) => storeAction.otherModel.foo
)
```

That should resolve the pain for you.

> And I was calling it fetch_listing(null). This doesn't work anymore.

Try the using a `void` instead.

```typescript
fetch_listing: Thunk<StateInterface, number | void, Injections>;
```

> I like the newer one - its feels more explicit. But I could not find the change documented anywhere.

Thanks for the heads up - I have added a placeholder on the v3 PR for now. I'll be expanding those docs as we get closer to its release.

-

Thanks again for this 👍

**Comment by pb03** [comment]
@ctrlplusb  Seems resolved with `easy-peasy@3.0.0-alpha.2`
Thanks man!

**Comment by hardfist** [comment]
The problem still exists in 3.0.2, you can check here https://github.com/hardfist/easy-peasy @ctrlplusb

**Comment by jmalins** [comment]
I am seeing this as well, on both Typescript 3.5.3 and 3.6.3. 

The error is a definite Heisenbug... phasing in and out of existence randomly. It will appear in VSCode and/or CRA app build, but not necessarily simultaneously or at the same place(s) in the code.

Also, it appears to only show up on `StateMapper`, so far I have not seen the problem on actions or listeners.

FWIW, I hacked the TS definition of the state mapper to reduce the recursion depth from `6` -> `4`. This seems to have fixed it.

**Comment by jamespacileo** [comment]
Still an issue here :(

`Type instantiation is excessively deep and possibly infinite`

**Comment by guilhermevdm** [comment]
I'm having the same issue 

> Type instantiation is excessively deep and possibly infinite.  TS2589

"easy-peasy": "^3.0.2",
 "react": "^16.10.1",
 "react-dom": "^16.10.1",
 "react-scripts": "3.1.2",
 "typescript": "3.6.3",

**Comment by ctrlplusb** [comment]
Thanks for the pr @jmalins - I shall review this week 👍

**Comment by DanielPe05** [comment]
Same issue here, has anyone found a work around this issue?

**Comment by ctrlplusb** [comment]
@DanielPe05 what version are you using?

**Comment by ctrlplusb** [comment]
Is anyone still experiencing this via the v3.1.0 release?

**Comment by guilhermevdm** [comment]
> Is anyone still experiencing this via the v3.1.0 release?

updating to v3.1.0 solved the issue for me

**Comment by samilCW** [comment]
This issue is causing also on `easy-peasy: "^3.3.0",`
Nothing was changed or upgraded. The error just showed up one day and on all the store declarations.
Tried upgrading `easy-peasy` to `5.0.3` and ts to `4.2.3` (current version 3.8.0), tried fresh yarn install, but didn't solve the error.
What's interesting about this issue is, it just showed up on production branch which didn't receive any recent changes. I wonder what could be the possible reason.
