### ISSUE TITLE
debug() is not unwrapping state

### ISSUE THREAD

**Issue by allpro** [ctrlplusb/easy-peasy#229]
I'm using the `debug()` helper inside an action with `console.log()`. However I'm _not_ getting the 'raw value' of state. My code is essentially the same as shown in the docs example so should be easily reproducable. **I'm using v2.6.5**

```javascript
  myAction: action((state, payload) => {
    console.log(debug(state)); // 👈 prints the "native" state representation
  })
```

This outputs:
```
Proxy {scope: ImmerScope, modified: false, finalized: false, assigned: {…}, parent: undefined, …}
[[Handler]]: null
[[Target]]: null
[[IsRevoked]]: true
```

**Comment by ctrlplusb** [comment]
Oh wow, hmm. Will look into this. Thanks

**Comment by ctrlplusb** [comment]
Yep, definitely something not right going on here. Thanks for the heads up. 👍

**Comment by ctrlplusb** [comment]
This should be fixed in `easy-peasy@3.0.0-alpha.10` 👍

**Comment by bmccord** [comment]
This is still happening.  Example at: https://codesandbox.io/s/easy-peasy-tutorial-computed-02di7

Look in basket-model.js.  Add an item to the basket.  Output is: 
Brian
common-sandbox.d6a25806.chunk.js:8 Proxy {scope: ImmerScope, modified: false, finalized: false, assigned: {…}, parent: {…}, …}
