### ISSUE TITLE
v3.0.0.rc-1 with disableImmer: true breaks nested stores

### ISSUE THREAD

**Issue by Awpteamoose** [ctrlplusb/easy-peasy#263]
Minimal repro:
```javascript
const easyPeasy = require("easy-peasy");

const model = {
	nested: {
		foo: 0,
		setFoo: easyPeasy.action((state, foo) => ({ ...state, foo })),
	},
};

const store = easyPeasy.createStore(model, { disableImmer: true });
console.log(store.getState()); // { nested: { foo: 0 } }
store.dispatch.nested.setFoo(5);
console.log(store.getState()); // undefined
```

**Comment by ctrlplusb** [comment]
Thanks for this @Awpteamoose - fix released in `easy-peasy@3.0.0-rc.2`.

**Comment by MarkySparky** [comment]
I'm still getting this issue whilst using nested stores in 3.0.2.

Can you confirm this was released for this version?

**Comment by Awpteamoose** [comment]
I'm on 3.0.2 and it was fixed for me. If my repro code runs ok for you then maybe you're hitting some other edge case.
